version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: safemeds-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - safemeds-net
    restart: unless-stopped

  safemeds-backend:
    build: .
    container_name: safemeds-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - safemeds-net
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  safemeds-net: